/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JogoDaForca;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Notebook
 */
public class Forca extends javax.swing.JFrame {

    /**
     * Creates new form Forca
     */
    public Forca(jogar j,String dica,String palavra,char[] vet,String p) {
        initComponents();
        this.jogo=j;
        hint.setText(String.valueOf(dica));
        word.setText(p);
        this.vet=vet;
        this.palavra=palavra;
        Forca1.setVisible(false);
        Forca2.setVisible(false);
        Forca3.setVisible(false);
        Forca4.setVisible(false);
        Forca5.setVisible(false);
        Forca6.setVisible(false);
    }
    jogar jogo;
    char[] vet;
    String dica,palavra;
    char letra;
    boolean t=false,j=false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Palavra = new javax.swing.JTextField();
        A = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        E = new javax.swing.JRadioButton();
        F = new javax.swing.JRadioButton();
        G = new javax.swing.JRadioButton();
        H = new javax.swing.JRadioButton();
        I = new javax.swing.JRadioButton();
        J = new javax.swing.JRadioButton();
        K = new javax.swing.JRadioButton();
        L = new javax.swing.JRadioButton();
        W = new javax.swing.JRadioButton();
        M = new javax.swing.JRadioButton();
        N = new javax.swing.JRadioButton();
        O = new javax.swing.JRadioButton();
        P = new javax.swing.JRadioButton();
        Q = new javax.swing.JRadioButton();
        R = new javax.swing.JRadioButton();
        S = new javax.swing.JRadioButton();
        T = new javax.swing.JRadioButton();
        U = new javax.swing.JRadioButton();
        V = new javax.swing.JRadioButton();
        X = new javax.swing.JRadioButton();
        nove = new javax.swing.JRadioButton();
        Y = new javax.swing.JRadioButton();
        Z = new javax.swing.JRadioButton();
        zero = new javax.swing.JRadioButton();
        um = new javax.swing.JRadioButton();
        dois = new javax.swing.JRadioButton();
        tres = new javax.swing.JRadioButton();
        quatro = new javax.swing.JRadioButton();
        cinco = new javax.swing.JRadioButton();
        seis = new javax.swing.JRadioButton();
        sete = new javax.swing.JRadioButton();
        oito = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        hint = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        yes = new javax.swing.JButton();
        word = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FundoForca = new javax.swing.JLabel();
        Forca1 = new javax.swing.JLabel();
        Forca2 = new javax.swing.JLabel();
        Forca3 = new javax.swing.JLabel();
        Forca4 = new javax.swing.JLabel();
        Forca5 = new javax.swing.JLabel();
        Forca6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Palavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalavraActionPerformed(evt);
            }
        });
        getContentPane().add(Palavra, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 260, 30));

        buttonGroup1.add(A);
        A.setText("A");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        getContentPane().add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        buttonGroup1.add(B);
        B.setText("B");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        getContentPane().add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        buttonGroup1.add(C);
        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        getContentPane().add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        buttonGroup1.add(D);
        D.setText("D");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        getContentPane().add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        buttonGroup1.add(E);
        E.setText("E");
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });
        getContentPane().add(E, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        buttonGroup1.add(F);
        F.setText("F");
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });
        getContentPane().add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        buttonGroup1.add(G);
        G.setText("G");
        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GActionPerformed(evt);
            }
        });
        getContentPane().add(G, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        buttonGroup1.add(H);
        H.setText("H");
        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActionPerformed(evt);
            }
        });
        getContentPane().add(H, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        buttonGroup1.add(I);
        I.setText("I");
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });
        getContentPane().add(I, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        buttonGroup1.add(J);
        J.setText("J");
        J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JActionPerformed(evt);
            }
        });
        getContentPane().add(J, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        buttonGroup1.add(K);
        K.setText("K");
        K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KActionPerformed(evt);
            }
        });
        getContentPane().add(K, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, -1));

        buttonGroup1.add(L);
        L.setText("L");
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });
        getContentPane().add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, -1));

        buttonGroup1.add(W);
        W.setText("W");
        W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WActionPerformed(evt);
            }
        });
        getContentPane().add(W, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, -1, -1));

        buttonGroup1.add(M);
        M.setText("M");
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });
        getContentPane().add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        buttonGroup1.add(N);
        N.setText("N");
        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });
        getContentPane().add(N, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        buttonGroup1.add(O);
        O.setText("O");
        O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OActionPerformed(evt);
            }
        });
        getContentPane().add(O, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        buttonGroup1.add(P);
        P.setText("P");
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });
        getContentPane().add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        buttonGroup1.add(Q);
        Q.setText("Q");
        Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QActionPerformed(evt);
            }
        });
        getContentPane().add(Q, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        buttonGroup1.add(R);
        R.setText("R");
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });
        getContentPane().add(R, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        buttonGroup1.add(S);
        S.setText("S");
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });
        getContentPane().add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        buttonGroup1.add(T);
        T.setText("T");
        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });
        getContentPane().add(T, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        buttonGroup1.add(U);
        U.setText("U");
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });
        getContentPane().add(U, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        buttonGroup1.add(V);
        V.setText("V");
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });
        getContentPane().add(V, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        buttonGroup1.add(X);
        X.setText("X");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });
        getContentPane().add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, -1, -1));

        buttonGroup1.add(nove);
        nove.setText("9");
        nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveActionPerformed(evt);
            }
        });
        getContentPane().add(nove, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        buttonGroup1.add(Y);
        Y.setText("Y");
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YActionPerformed(evt);
            }
        });
        getContentPane().add(Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        buttonGroup1.add(Z);
        Z.setText("Z");
        Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZActionPerformed(evt);
            }
        });
        getContentPane().add(Z, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        buttonGroup1.add(zero);
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        getContentPane().add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        buttonGroup1.add(um);
        um.setText("1");
        um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umActionPerformed(evt);
            }
        });
        getContentPane().add(um, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        buttonGroup1.add(dois);
        dois.setText("2");
        dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisActionPerformed(evt);
            }
        });
        getContentPane().add(dois, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        buttonGroup1.add(tres);
        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        getContentPane().add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        buttonGroup1.add(quatro);
        quatro.setText("4");
        quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroActionPerformed(evt);
            }
        });
        getContentPane().add(quatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        buttonGroup1.add(cinco);
        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        getContentPane().add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));

        buttonGroup1.add(seis);
        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        getContentPane().add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, -1, -1));

        buttonGroup1.add(sete);
        sete.setText("7");
        sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteActionPerformed(evt);
            }
        });
        getContentPane().add(sete, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        buttonGroup1.add(oito);
        oito.setText("8");
        oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitoActionPerformed(evt);
            }
        });
        getContentPane().add(oito, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, -1, -1));

        jLabel1.setText("Dica:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        hint.setEditable(false);
        hint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintActionPerformed(evt);
            }
        });
        getContentPane().add(hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 539, -1));

        jLabel2.setText("Já Sabe? Pode arriscar aqui ->");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, -1, -1));

        yes.setText("Confima a letra?");
        yes.setEnabled(false);
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });
        getContentPane().add(yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));

        word.setEditable(false);
        word.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordActionPerformed(evt);
            }
        });
        getContentPane().add(word, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 532, -1));

        jLabel3.setText("Palavra:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        FundoForca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JogoDaForca/Imagens/ForcaFundo.jpg"))); // NOI18N
        getContentPane().add(FundoForca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Forca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JogoDaForca/Imagens/Forca1.jpg"))); // NOI18N
        getContentPane().add(Forca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Forca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JogoDaForca/Imagens/Forca2.jpg"))); // NOI18N
        getContentPane().add(Forca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Forca3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JogoDaForca/Imagens/Forca3.jpg"))); // NOI18N
        getContentPane().add(Forca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Forca4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JogoDaForca/Imagens/Forca4.jpg"))); // NOI18N
        getContentPane().add(Forca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Forca5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JogoDaForca/Imagens/Forca5.jpg"))); // NOI18N
        getContentPane().add(Forca5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Forca6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JogoDaForca/Imagens/Forca6.jpg"))); // NOI18N
        getContentPane().add(Forca6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalavraActionPerformed
        // TODO add your handling code here:
        if (Palavra.getText().equals(palavra)){
            word.setText(palavra);
            j=true;
            yes.setEnabled(true);
            yes.doClick();
        }
        else{
            letra='%';
            t=true;
            yes.setEnabled(true);
            yes.doClick();
        }
    }//GEN-LAST:event_PalavraActionPerformed

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        // TODO add your handling code here:
        letra='i';
        yes.setEnabled(true);
    }//GEN-LAST:event_IActionPerformed

    private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
        // TODO add your handling code here:
        letra='l';
        yes.setEnabled(true);
    }//GEN-LAST:event_LActionPerformed

    private void KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KActionPerformed
        // TODO add your handling code here:
        letra='k';
        yes.setEnabled(true);
    }//GEN-LAST:event_KActionPerformed

    private void JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JActionPerformed
        // TODO add your handling code here:
        letra='j';
        yes.setEnabled(true);
    }//GEN-LAST:event_JActionPerformed

    private void WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WActionPerformed
        // TODO add your handling code here:
        letra='w';
        yes.setEnabled(true);
    }//GEN-LAST:event_WActionPerformed

    private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
        // TODO add your handling code here:
        letra='u';
        yes.setEnabled(true);
    }//GEN-LAST:event_UActionPerformed

    private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
        // TODO add your handling code here:
        letra='v';
        yes.setEnabled(true);
    }//GEN-LAST:event_VActionPerformed

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        // TODO add your handling code here:
        letra='x';
        yes.setEnabled(true);
    }//GEN-LAST:event_XActionPerformed

    private void noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveActionPerformed
        // TODO add your handling code here:
        letra='9';
        yes.setEnabled(true);
    }//GEN-LAST:event_noveActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // TODO add your handling code here:
        letra='6';
        yes.setEnabled(true);
    }//GEN-LAST:event_seisActionPerformed

    private void seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteActionPerformed
        // TODO add your handling code here:
        letra='7';
        yes.setEnabled(true);
    }//GEN-LAST:event_seteActionPerformed

    private void oitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitoActionPerformed
        // TODO add your handling code here:
        letra='8';
        yes.setEnabled(true);
    }//GEN-LAST:event_oitoActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        // TODO add your handling code here:
        letra='e';
        yes.setEnabled(true);
    }//GEN-LAST:event_EActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        // TODO add your handling code here:
        letra='f';
        yes.setEnabled(true);
    }//GEN-LAST:event_FActionPerformed

    private void ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZActionPerformed
        // TODO add your handling code here:
        letra='z';
        yes.setEnabled(true);
    }//GEN-LAST:event_ZActionPerformed

    private void hintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintActionPerformed
        // TODO add your handling code here:
        hint.setText(String.valueOf(dica));
    }//GEN-LAST:event_hintActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
        letra='a';
        yes.setEnabled(true);
    }//GEN-LAST:event_AActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
        letra='b';
        yes.setEnabled(true);
    }//GEN-LAST:event_BActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
        letra='c';
        yes.setEnabled(true);
    }//GEN-LAST:event_CActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        // TODO add your handling code here:
        letra='d';
        yes.setEnabled(true);
    }//GEN-LAST:event_DActionPerformed

    private void GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GActionPerformed
        // TODO add your handling code here:
        letra='g';
        yes.setEnabled(true);
    }//GEN-LAST:event_GActionPerformed

    private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
        // TODO add your handling code here:
        letra='h';
        yes.setEnabled(true);
    }//GEN-LAST:event_HActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        // TODO add your handling code here:
        letra='m';
        yes.setEnabled(true);
    }//GEN-LAST:event_MActionPerformed

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
        // TODO add your handling code here:
        letra='n';
        yes.setEnabled(true);
    }//GEN-LAST:event_NActionPerformed

    private void OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OActionPerformed
        // TODO add your handling code here:
        letra='o';
        yes.setEnabled(true);
    }//GEN-LAST:event_OActionPerformed

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        // TODO add your handling code here:
        letra='p';
        yes.setEnabled(true);
    }//GEN-LAST:event_PActionPerformed

    private void QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QActionPerformed
        // TODO add your handling code here:
        letra='q';
        yes.setEnabled(true);
    }//GEN-LAST:event_QActionPerformed

    private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
        // TODO add your handling code here:
        letra='r';
        yes.setEnabled(true);
    }//GEN-LAST:event_RActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
        // TODO add your handling code here:
        letra='s';
        yes.setEnabled(true);
    }//GEN-LAST:event_SActionPerformed

    private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
        // TODO add your handling code here:
        letra='t';
        yes.setEnabled(true);
    }//GEN-LAST:event_TActionPerformed

    private void YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YActionPerformed
        // TODO add your handling code here:
        letra='y';
        yes.setEnabled(true);
    }//GEN-LAST:event_YActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:letra='a';
        letra='0';
        yes.setEnabled(true);
    }//GEN-LAST:event_zeroActionPerformed

    private void umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umActionPerformed
        // TODO add your handling code here:
        letra='1';
        yes.setEnabled(true);
    }//GEN-LAST:event_umActionPerformed

    private void doisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doisActionPerformed
        // TODO add your handling code here:
        letra='2';
        yes.setEnabled(true);
    }//GEN-LAST:event_doisActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        // TODO add your handling code here:
        letra='3';
        yes.setEnabled(true);
    }//GEN-LAST:event_tresActionPerformed

    private void quatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatroActionPerformed
        // TODO add your handling code here:
        letra='4';
        yes.setEnabled(true);
    }//GEN-LAST:event_quatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        // TODO add your handling code here:
        letra='5';
        yes.setEnabled(true);
    }//GEN-LAST:event_cincoActionPerformed

    private void wordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        // TODO add your handling code here:
        boolean m=false;
        if (!j && !t){
             buttonGroup1.getSelection().setEnabled(false);
             word.setText(jogo.jogando(letra, vet));
        }
        if (t) {
            word.setText(jogo.jogando(letra,vet));
            t=false;
        }
        yes.setEnabled(false);
        if (jogo.lifes==5) {
                    FundoForca.setVisible(false);
                    Forca1.setVisible(true);
                    Forca2.setVisible(false);
                    Forca3.setVisible(false);
                    Forca4.setVisible(false);
                    Forca5.setVisible(false);
                    Forca6.setVisible(false);
            }else if(jogo.lifes==4) {
                    FundoForca.setVisible(false);
                    Forca1.setVisible(false);
                    Forca2.setVisible(true);
                    Forca3.setVisible(false);
                    Forca4.setVisible(false);
                    Forca5.setVisible(false);
                    Forca6.setVisible(false);
            }else if(jogo.lifes==3){
                
                    FundoForca.setVisible(false);
                    Forca1.setVisible(false);
                    Forca2.setVisible(false);
                    Forca3.setVisible(true);
                    Forca4.setVisible(false);
                    Forca5.setVisible(false);
                    Forca6.setVisible(false);
                
            }else if(jogo.lifes==2){
                
                    FundoForca.setVisible(false);
                    Forca1.setVisible(false);
                    Forca2.setVisible(false);
                    Forca3.setVisible(false);
                    Forca4.setVisible(true);
                    Forca5.setVisible(false);
                    Forca6.setVisible(false);
                    
            }else if(jogo.lifes==1) {
                
                    FundoForca.setVisible(false);
                    Forca1.setVisible(false);
                    Forca2.setVisible(false);
                    Forca3.setVisible(false);
                    Forca4.setVisible(false);
                    Forca5.setVisible(true);
                    Forca6.setVisible(false);
                
            
            }else if (jogo.lifes==0){
                yes.setEnabled(false);
                Palavra.setEnabled(false);
                FundoForca.setVisible(false);
                Forca1.setVisible(false);
                Forca2.setVisible(false);
                Forca3.setVisible(false);
                Forca4.setVisible(false);
                Forca5.setVisible(false);
                Forca6.setVisible(true);
                JOptionPane.showMessageDialog(null,"A palavra era: "+palavra,"Você Perdeu :( ",0);
                int v=JOptionPane.showConfirmDialog(null,"Deseja tentar novamente ?", "", 0, 1);
                if(v==0){
                    m=true;
                }
            }
        if(jogo.checarVitoria()|| m || j){
            int c=1;
            if(m){
                c=0;
            }else{
                JOptionPane.showMessageDialog(null,"Parabéns você conseguiu!!");
                c=JOptionPane.showConfirmDialog(null,"Deseja tentar novamente ?","Parabéns você conseguiu!!", 0);
            }
            if (c==0){
                int ad []=jogo.novamente();
                int h=ad[0],d=ad[1];
                this.setVisible(false);
                try{
                    String [] a=jogo.jogo(h,d);
                    String word="";
                    char vet[]=jogo.tochar(a);
                    jogo.acertos= new boolean [vet.length];
                    for (int i = 0; i < vet.length; i++) {
                        if (vet[i]=='-'|| vet[i]=='.'|| vet[i]==' '|| vet[i]==',') {
                            jogo.acertos[i]=true;
                        }else{
                            jogo.acertos[i]=false;
                        }
                    }
                    for (int i = 0; i < vet.length; i++) {
                        if(jogo.acertos[i]){
                            word=word+vet[i]+" ";
                        }else{
                            word=word+"_ ";
                        }
                    }
                    Forca f = new Forca(jogo,a[1],a[0],vet,word);
                    f.setVisible(true);
                }
                catch (IOException e){
                    System.out.println("Erro");
                }
            }else{
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_yesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.JRadioButton D;
    private javax.swing.JRadioButton E;
    private javax.swing.JRadioButton F;
    private javax.swing.JLabel Forca1;
    private javax.swing.JLabel Forca2;
    private javax.swing.JLabel Forca3;
    private javax.swing.JLabel Forca4;
    private javax.swing.JLabel Forca5;
    private javax.swing.JLabel Forca6;
    private javax.swing.JLabel FundoForca;
    private javax.swing.JRadioButton G;
    private javax.swing.JRadioButton H;
    private javax.swing.JRadioButton I;
    private javax.swing.JRadioButton J;
    private javax.swing.JRadioButton K;
    private javax.swing.JRadioButton L;
    private javax.swing.JRadioButton M;
    private javax.swing.JRadioButton N;
    private javax.swing.JRadioButton O;
    private javax.swing.JRadioButton P;
    private javax.swing.JTextField Palavra;
    private javax.swing.JRadioButton Q;
    private javax.swing.JRadioButton R;
    private javax.swing.JRadioButton S;
    private javax.swing.JRadioButton T;
    private javax.swing.JRadioButton U;
    private javax.swing.JRadioButton V;
    private javax.swing.JRadioButton W;
    private javax.swing.JRadioButton X;
    private javax.swing.JRadioButton Y;
    private javax.swing.JRadioButton Z;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cinco;
    private javax.swing.JRadioButton dois;
    private javax.swing.JTextField hint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton nove;
    private javax.swing.JRadioButton oito;
    private javax.swing.JRadioButton quatro;
    private javax.swing.JRadioButton seis;
    private javax.swing.JRadioButton sete;
    private javax.swing.JRadioButton tres;
    private javax.swing.JRadioButton um;
    private javax.swing.JTextField word;
    private javax.swing.JButton yes;
    private javax.swing.JRadioButton zero;
    // End of variables declaration//GEN-END:variables
}
